spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/allamiro_renhold
spring.datasource.username=postgres
spring.datasource.password=max2004xim

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect